import java.util.Scanner;
import java.util.Random;


class Task_1
{
    public static void main(String args[])
    {
    Scanner sc = new Scanner(System.in);
    int temp,i,flag,j,fact,atm;
    temp=0;
    flag=1;
    atm=1;
    System.out.println("*****RULES*****");
    System.out.println("You Have to guess a number from 1 to 100, A random number will be Generated By computer");
    System.out.println("You will have Total of 5 Attempts in each Round");
    System.out.println("You can Play how many Rounds as you want");
    System.out.println("At Last, Your Score will be Generated");
    System.out.println("");
    System.out.println("");
    System.out.println("How many Rounds You want to Play?");
    int a=sc.nextInt();
    Random ro=new Random();
    for(i=0;i<a;i++)
    {
        atm=1;
        int ra=ro.nextInt(100);
        for(j=0;j<5;j++)
        {
            fact=ra;
            System.out.println("");
            System.out.println("");
            System.out.println("");
            System.out.println("*****ATTEMPT NUMBER:" + atm);
            atm++;
            System.out.print("Enter Number:");
            int num=sc.nextInt();
            if(num>fact)
            {
                System.out.println("Go Low");
            }
            else if(num<fact)
            {
                System.out.println("Go High");
            }
            else if(num==fact)
            {
                System.out.println("Perfect Number");
                temp++;
                break;
            }
            else
            {
                System.out.println("Enter Valid Number");
            }
        }
        System.out.println("Your " + flag + " round has been Completed!");
        flag++;
        System.out.println("");
        System.out.println("");
    }
    System.out.println(""); 
    System.out.println("");
    
    System.out.println("***RESULT TIME***");
    System.out.println("You have completed all your Rounds");
    System.out.println("Your Score:" + temp + "/" + a);
    }
}